### ISSUE TITLE
Simple SV normalization algorithm

### ISSUE THREAD

**Issue by Bestfast** [Eve-ning/reamberPy#110]
**Describe your algorithm in as few sentences as possible**
Normalize the SV of a chart based on multiple BPM points. This is a common algorithm that could be useful for people who map multi bpm charts or for NSV implementation(?)

**Comment by Eve-ning** [comment]
It was originally in my previously deprecated `sv` package. I found it too messy to maintain so I had to drop it.
I'll see if I have capacity to implement this though, but I can't guarantee it'll be soon.
