### ISSUE TITLE
Handle unicode characters for Tags, Title, Author etc

### ISSUE THREAD

**Issue by Bestfast** [Eve-ning/reamberPy#38]
**Describe the bug**
Currently letters like é (LATIN SMALL LETTER E WITH ACUTE) aren't correctly handled and will output \x?? instead of the correct character.

**Comment by Eve-ning** [comment]
this is with the same map as #37? the qua is already using it

`Title: "Amn\xE9hilesie"`

**Comment by Bestfast** [comment]
https://quavergame.com/mapset/map/14686 this is the original mapset if you want to check it

**Comment by Eve-ning** [comment]
Will be a bit before I get back to this, working on something else rn

**Comment by Bestfast** [comment]
If it's fine for you, I might just fix it and open a PR for both this and #37. It will be my first PR though

**Comment by Eve-ning** [comment]
Fixed unicode issues in #42
