### ISSUE TITLE
Typo in the docs

### ISSUE THREAD

**Issue by Bestfast** [Eve-ning/reamberPy#56]
Examples: 
https://eve-ning.github.io/reamberPy/reamber/algorithms/convert.html#to-quaver

`quaMapSet = SMToOsu.convert(sm)` should be `quaMapSet = SMToQua.convert(sm)`

I don't know if there are others, but might be worth checking.

**Comment by Eve-ning** [comment]
Fixed by 3d0b935f0ebe052925dbf7019d00ecc2bd1185a0
