### ISSUE TITLE
Implement MinaCalc and Star Rating system 

### ISSUE THREAD

**Issue by Bestfast** [Eve-ning/reamberPy#57]
Reference:

1. Minacalc:

- https://github.com/etternagame/etterna/tree/develop/src/Etterna/MinaCalc

- https://github.com/kangalioo/Minacalc/tree/b9706e9a1add23127cbdb7c6bc5b3891840c4a41

 2. Star Rating:

- https://github.com/ppy/osu/tree/master/osu.Game.Rulesets.Mania/Difficulty

**Comment by Eve-ning** [comment]
Probably going to be very low priority because

1) Algorithm is volatile 
2) Don't have time to understand everything
3) Maintainence is very time expensive

**Comment by Eve-ning** [comment]
ok please use those separately then, reamber won't support star rating as it's way too time expensive
