### ISSUE TITLE
FLN Algorithm

### ISSUE THREAD

**Issue by Eve-ning** [Eve-ning/reamberPy#70]
**Describe your algorithm in as few sentences as possible**

**If possible, add your algorithm pseudo or python code**

**Comment by IceDynamix** [comment]
simple O(n) algorithm for fln, assumes that notes and bpms are ordered by time
```py
gapSnap = 4
minGap = 20

newNotes = []
currentNotes = [None for i in keyCount]
bpmIndex = 0
bpm = bpms[0]

for nextNote in notes:
  # first note in the lane
  if currentNotes[nextNote.lane] is None:
    currentNotes[nextNote.lane] = note
    continue

  currentNote = currentNotes[nextNote.lane]

  if bpmIndex < len(bpms) and bpms[bpmIndex].offset < currentNote.offset:
    bpmIndex += 1
    bpm = bpms[bpmIndex]
  
  lnGap = 60000/bpm/gapSnap

  if nextNote.offset - currentNote.offset > minGap:
      currentNote.lnEnd = nextNote.offset - lnGap

  newNotes.append(currentNote)
  currentNotes[note.lane] = nextNote
```
things get more complex if inverse is desired (inverse > fln btw), you can take a look at the [inverse algorithm used in quaver](https://github.com/Quaver/Quaver.API/blob/master/Quaver.API/Maps/Qua.cs#L710)

**Comment by IceDynamix** [comment]
clarification: inverse is fln but lns are turned into gaps, quaver handles fln by converting all lns to regular notes before applying the inverse algorithm

**Comment by Eve-ning** [comment]
Added, new release v0.1.7
