### ISSUE TITLE
Overlapped notes when changing rate

### ISSUE THREAD

**Issue by Bestfast** [Eve-ning/reamberPy#74]
**Describe the bug**
 Changing rate of some maps doesn't fully work and gives overlapped notes as a result

**Files used (if any)**
 
https://osu.ppy.sh/beatmapsets/1599290#mania/3266313 changing rate to 1.15

**Comment by Eve-ning** [comment]
Seems like it's solved somewhere in my 0.1.6 version, thanks for reporting it regardless!
![image](https://user-images.githubusercontent.com/26498608/178277475-40c64356-4153-4c55-9e39-6a57549df90d.png)
